version: "3"

silent: true

dotenv: [".env"]

vars:
  # Paths
  PATH_REPO_ROOT:
    sh: git rev-parse --show-toplevel
  PATH_BUILD_ARTIFACTS: '{{joinPath .PATH_REPO_ROOT ".build-artifacts"}}'
  PATH_CRATES: '{{joinPath .PATH_REPO_ROOT "crates"}}'
  PATH_BUILD_ARTIFACTS_FRONTEND: '{{joinPath .PATH_BUILD_ARTIFACTS "frontend"}}'
  PATH_MEDIA_LOCAL: '{{joinPath .PATH_REPO_ROOT "media"}}'
  PATH_MEDIA_ADDITIONAL_ASSETS: '{{joinPath .PATH_REPO_ROOT ".." "awsm-renderer-assets"}}'
  PATH_CRATE_FRONTEND: '{{joinPath .PATH_CRATES "frontend"}}'
  PATH_CRATE_RENDERER: '{{joinPath .PATH_CRATES "renderer"}}'
  PATH_CRATE_RENDERER_CORE: '{{joinPath .PATH_CRATES "renderer-core"}}'

  # Ports
  PORT_MEDIA_LOCAL_DEV: 9082
  PORT_MEDIA_ADDITIONAL_ASSETS_DEV: 9083
  PORT_FRONTEND_DEV: 9080

  # URLs
  URL_PROD_MEDIA_BASE_URL_GLTF_SAMPLES: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/refs/heads/main/Models"
  URL_PROD_MEDIA_BASE_URL_ADDITIONAL_ASSETS: "https://dakom.github.io/awsm-renderer-assets"
  URL_DEV_MEDIA_BASE_URL_GLTF_SAMPLES: "http://localhost:{{.PORT_MEDIA_LOCAL_DEV}}/glTF-Sample-Assets/Models"
  URL_DEV_MEDIA_BASE_URL_ADDITIONAL_ASSETS: "http://localhost:{{.PORT_MEDIA_ADDITIONAL_ASSETS_DEV}}"
  URL_TRUNK: "https://dakom.github.io/awsm-renderer/"

  # Misc
  PROD_ROOT_BASE_URI_PATH: "/awsm-renderer"
  DEV_ROOT_BASE_URI_PATH: ""

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task --list-all
  dev:
    deps: [media-local, media-additional-assets, trunk-serve]
    desc: "Run frontend development server"

  trunk-serve:
    internal: true
    desc: "Trunk serve"
    env:
      MEDIA_BASE_URL_GLTF_SAMPLES: "{{.URL_DEV_MEDIA_BASE_URL_GLTF_SAMPLES}}"
      MEDIA_BASE_URL_ADDITIONAL_ASSETS: "{{.URL_DEV_MEDIA_BASE_URL_ADDITIONAL_ASSETS}}"
      ROOT_BASE_URI_PATH: "{{.DEV_ROOT_BASE_URI_PATH}}"
    cmds:
      - >
        cd {{.PATH_CRATE_FRONTEND}} &&
        trunk serve --port {{.PORT_FRONTEND_DEV}}
        --watch "{{.PATH_MEDIA_LOCAL}}"
        --watch "{{.PATH_MEDIA_ADDITIONAL_ASSETS}}"
        --watch "{{.PATH_CRATE_FRONTEND}}"
        --watch "{{.PATH_CRATE_RENDERER}}"
        --watch "{{.PATH_CRATE_RENDERER_CORE}}"

  media-local:
    internal: true
    desc: "Local media server"
    cmds:
      - >
        cd {{.PATH_MEDIA_LOCAL}} &&
        http-server --gzip --cors -p {{.PORT_MEDIA_LOCAL_DEV}}

  media-additional-assets:
    internal: true
    desc: "Additional assets media server"
    cmds:
      - >
        cd {{.PATH_MEDIA_ADDITIONAL_ASSETS}} &&
        http-server --gzip --cors -p {{.PORT_MEDIA_ADDITIONAL_ASSETS_DEV}}

  build:
    deps: [trunk-build-release]
    desc: "Build frontend for production"
    cmds:
      # no need to copy media, it's referenced remotely in production
      - mkdir -p {{.PATH_BUILD_ARTIFACTS_FRONTEND}}
      - cp -r {{joinPath .PATH_CRATE_FRONTEND "dist" }}/* {{.PATH_BUILD_ARTIFACTS_FRONTEND}}/
      - cp {{joinPath .PATH_CRATE_FRONTEND "index.html" }} {{joinPath .PATH_BUILD_ARTIFACTS_FRONTEND "404.html"}}

  trunk-build-release:
    internal: true
    desc: "Trunk build release"
    env:
      MEDIA_BASE_URL_GLTF_SAMPLES: "{{.URL_PROD_MEDIA_BASE_URL_GLTF_SAMPLES}}"
      MEDIA_BASE_URL_ADDITIONAL_ASSETS: "{{.URL_PROD_MEDIA_BASE_URL_ADDITIONAL_ASSETS}}"
      ROOT_BASE_URI_PATH: "{{.PROD_ROOT_BASE_URI_PATH}}"
    cmds:
      - >
        cd {{.PATH_CRATE_FRONTEND}} &&
        trunk build --release --public-url "{{.URL_TRUNK}}"
