[target.wasm32-unknown-unknown]
rustflags = ["--cfg=web_sys_unstable_apis", "--cfg=getrandom_backend=\"wasm_js\""]

# event though we don't really need this for all crates, it's easier to make the IDE happy this way
[target.'cfg(not(target_arch = "wasm32"))']
rustflags = ["--cfg=web_sys_unstable_apis"]