pub const BIND_GROUP_CAMERA: u32 = 0;
pub const BIND_GROUP_CAMERA_BINDING: u32 = 0;

pub const BIND_GROUP_TRANSFORM: u32 = 1;
pub const BIND_GROUP_TRANSFORM_BINDING: u32 = 0;

pub const BIND_GROUP_MORPH_TARGET_WEIGHTS: u32 = 2;
pub const BIND_GROUP_MORPH_TARGET_WEIGHTS_BINDING: u32 = 0;

pub const BIND_GROUP_MORPH_TARGET_VALUES: u32 = 3;
pub const BIND_GROUP_MORPH_TARGET_VALUES_BINDING: u32 = 0;
